export const perms = [
    "category",
    "article",
    "slide",
    "tag",
    "collect",
    "gather",
    "model",
    "field",
    "friendlink",
    "message",
    "user",
    "role",
    "menu",
  ]